#!/bin/bash

if [[ -e "lisp" ]]; then
    sbcl --non-interactive \
         --load lisp/setup.lisp \
         --eval '(push #P"./" asdf:*central-registry*)' \
         --eval '(ql:quickload "{{cookiecutter.project_name}}-dev")'
else
    curl -O http://beta.quicklisp.org/quicklisp.lisp
    trap 'rm quicklisp.lisp' EXIT

    sbcl --non-interactive \
         --load quicklisp.lisp \
         --eval '(quicklisp-quickstart:install :path #P"./lisp")' \
         --eval '(push #P"./" asdf:*central-registry*)' \
         --eval '(ql:quickload "{{cookiecutter.project_name}}-dev")'
fi
